deployments:
  MyWebApp:
    dockerimage: ubuntu:14.04
    build_steps:
      - apt-get update && apt-get install -y libssl-dev \
        libpq-dev git \
        python python-dev python-pip python-virtualenv
      - pip install setuptools pip
      - pip install ~/code
      - lscpu
    launch_steps:
      - cd ~/code/mysite
      - python manage.py runserver 0.0.0.0:80
